weblog: yes
#backlog: yes

sonofs:
  - sonoff_26575D-5981.local
  - sonoff_68AC8D-3213.local

commands:
    #Return response as Command topic
  - "SetOption4 1"
    #Set ButtonTopic to Topic and enable MQTT retain flag on button press
  - "SwitchRetain 1"
    #Enable MQTT power retain on status update
  - "PowerRetain 1"
    #set Timezone
  - "Timezone 3"
    #set Geo
  - "Latitude 60.1808"
  - "Longitude 29.3935"
    #set no reboot on nonetwork
  - "WifiConfig 5"

  - "status 0"