weblog: yes
#backlog: yes

sonoffs:
  - sonoff_68B5C7
  - sonoff_95B510

_hosts:
  - sonoff_F4BC40-7232.local
  - sonoff_95B510-5392.local
  

commands:
    #period for publish tele
  - "TelePeriod 180"
  - "status 0"
  - "Timers ?"
